In [1]:
import numpy as np
import pandas as pd

In [85]:
n=14
np.random.seed(45)
name=['Jordyn','Alex','Kasey','Matthew','Lili','Sophia','Debby','Howard','Jace','Rosy','Jasmin','Toni','Robby','Maddy']
hrs=np.random.randint(8,20,n)
credit=np.random.randint(12,21,n)
school=np.random.choice(['SOB','COAS','SOC','CNAHS','CEA'],n)
student_data=pd.DataFrame(hrs,columns=['Weekly_Hrs_Spent_Studying'])
student_data

    Weekly_Hrs_Spent_Studying
0                          19
1                          11
2                           8
3                          13
4                          11
5                          12
6                          17
7                          16
8                           9
9                          13
10                         17
11                         14
12                         16
13                         15

In [86]:
student_data.insert(0,'#_of_Credit',credit)

In [87]:
student_data.insert(0,'School',school)

In [88]:
student_data.insert(0,'Name',name)

In [89]:
student_data

       Name School  #_of_Credit  Weekly_Hrs_Spent_Studying
0    Jordyn    SOB           20                         19
1      Alex   COAS           17                         11
2     Kasey  CNAHS           14                          8
3   Matthew  CNAHS           20                         13
4      Lili    SOC           13                         11
5    Sophia    SOB           18                         12
6     Debby    CEA           16                         17
7    Howard   COAS           20                         16
8      Jace    SOB           16                          9
9      Rosy    SOB           18                         13
10   Jasmin   COAS           16                         17
11     Toni    SOC           13                         14
12    Robby  CNAHS           18                         16
13    Maddy    SOB           20                         15

In [90]:
#add an extra column not listed in the table
def majors(name):
    if name =='Jordyn':
        return 'Finance'
    elif name =='Alex':
        return 'Physics'
    elif name =='Kasey':
        return 'Nursing'
    elif name =='Matthew':
        return 'Physical Therapy'
    elif name =='Lili':
        return 'Advertising'
    elif name =='Sophia':
        return 'Marketing'
    elif name =='Debby':
        return 'Chemical Engineering'
    elif name =='Howard':
        return 'Biology'
    elif name =='Jace':
        return 'Finance'
    elif name =='Rosy':
        return 'Journalism and Media'
    elif name =='Jasmin':
        return 'Chemistry'
    elif name =='Toni':
        return 'Journalism'
    elif name =='Robby':
        return 'Nursing'
    else:
        return 'Business'

student_data['Major']=student_data['Name'].apply(majors)

In [91]:
student_data

,Name,School,#_of_Credit,Weekly_Hrs_Spent_Studying,Major
0,Jordyn,SOB,20,19,Finance
1,Alex,COAS,17,11,Physics
2,Kasey,CNAHS,14,8,Nursing
3,Matthew,CNAHS,20,13,Physical Therapy
4,Lili,SOC,13,11,Advertising
5,Sophia,SOB,18,12,Marketing
6,Debby,CEA,16,17,Chemical Engineering
7,Howard,COAS,20,16,Biology
8,Jace,SOB,16,9,Finance
9,Rosy,SOB,18,13,Journalism and Media
10,Jasmin,COAS,16,17,Chemistry
11,Toni,SOC,13,14,Journalism
12,Robby,CNAHS,18,16,Nursing
13,Maddy,SOB,20,15,Business

In [92]:
#save DF as a CSV file
student_data.to_csv('student_data_collected.csv',index=False)

In [93]:
#read CSV file and store as df
pd.read_csv('student_data_collected.csv')
df=pd.read_csv('student_data_collected.csv')
df

,Name,School,#_of_Credit,Weekly_Hrs_Spent_Studying,Major
0,Jordyn,SOB,20,19,Finance
1,Alex,COAS,17,11,Physics
2,Kasey,CNAHS,14,8,Nursing
3,Matthew,CNAHS,20,13,Physical Therapy
4,Lili,SOC,13,11,Advertising
5,Sophia,SOB,18,12,Marketing
6,Debby,CEA,16,17,Chemical Engineering
7,Howard,COAS,20,16,Biology
8,Jace,SOB,16,9,Finance
9,Rosy,SOB,18,13,Journalism and Media
10,Jasmin,COAS,16,17,Chemistry
11,Toni,SOC,13,14,Journalism
12,Robby,CNAHS,18,16,Nursing
13,Maddy,SOB,20,15,Business

In [94]:
#display first 2 rows of DF
df.head(3)

     Name School  #_of_Credit  Weekly_Hrs_Spent_Studying    Major
0  Jordyn    SOB           20                         19  Finance
1    Alex   COAS           17                         11  Physics
2   Kasey  CNAHS           14                          8  Nursing

In [95]:
#display last 2 rows of DF
df.tail(3)

     Name School  #_of_Credit  Weekly_Hrs_Spent_Studying       Major
11   Toni    SOC           13                         14  Journalism
12  Robby  CNAHS           18                         16     Nursing
13  Maddy    SOB           20                         15    Business

In [96]:
#check shape of DF
df.shape

(14, 5)

In [97]:
#display column names
df.columns

Index(['Name', 'School', '#_of_Credit', 'Weekly_Hrs_Spent_Studying', 'Major'], dtype='object')

In [98]:
#display the summary of the data
df.info

<bound method DataFrame.info of        Name School  #_of_Credit  Weekly_Hrs_Spent_Studying  \
0    Jordyn    SOB           20                         19
1      Alex   COAS           17                         11
2     Kasey  CNAHS           14                          8
3   Matthew  CNAHS           20                         13
4      Lili    SOC           13                         11
5    Sophia    SOB           18                         12
6     Debby    CEA           16                         17
7    Howard   COAS           20                         16
8      Jace    SOB           16                          9
9      Rosy    SOB           18                         13
10   Jasmin   COAS           16                         17
11     Toni    SOC           13                         14
12    Robby  CNAHS           18                         16
13    Maddy    SOB           20                         15

                   Major
0                Finance
1                Physics
2                Nursing
3       Physical Therapy
4            Advertising
5              Marketing
6   Chemical Engineering
7                Biology
8                Finance
9   Journalism and Media
10             Chemistry
11            Journalism
12               Nursing
13              Business  >

In [99]:
#rename the #_of_Credit column to Credit_hours
df.rename(columns={'#_of_Credit':'Credit_hours'},inplace=True)
df

,Name,School,Credit_hours,Weekly_Hrs_Spent_Studying,Major
0,Jordyn,SOB,20,19,Finance
1,Alex,COAS,17,11,Physics
2,Kasey,CNAHS,14,8,Nursing
3,Matthew,CNAHS,20,13,Physical Therapy
4,Lili,SOC,13,11,Advertising
5,Sophia,SOB,18,12,Marketing
6,Debby,CEA,16,17,Chemical Engineering
7,Howard,COAS,20,16,Biology
8,Jace,SOB,16,9,Finance
9,Rosy,SOB,18,13,Journalism and Media
10,Jasmin,COAS,16,17,Chemistry
11,Toni,SOC,13,14,Journalism
12,Robby,CNAHS,18,16,Nursing
13,Maddy,SOB,20,15,Business

In [100]:
#display only the major column
df['Major']

0                  Finance
1                  Physics
2                  Nursing
3         Physical Therapy
4              Advertising
5                Marketing
6     Chemical Engineering
7                  Biology
8                  Finance
9     Journalism and Media
10               Chemistry
11              Journalism
12                 Nursing
13                Business
Name: Major, dtype: object

In [101]:
#filtering the DF by showing the rows that have more than 15 credit hrs
df_filter=df[df['Credit_hours']>15]
df_filter

,Name,School,Credit_hours,Weekly_Hrs_Spent_Studying,Major
0,Jordyn,SOB,20,19,Finance
1,Alex,COAS,17,11,Physics
3,Matthew,CNAHS,20,13,Physical Therapy
5,Sophia,SOB,18,12,Marketing
6,Debby,CEA,16,17,Chemical Engineering
7,Howard,COAS,20,16,Biology
8,Jace,SOB,16,9,Finance
9,Rosy,SOB,18,13,Journalism and Media
10,Jasmin,COAS,16,17,Chemistry
12,Robby,CNAHS,18,16,Nursing
13,Maddy,SOB,20,15,Business

In [102]:
#find the maximum credit hours taken by a student
max_df=df['Credit_hours'].max()
max_df

20

In [103]:
#sort the DF by Major 
df_sorted=df.sort_values(by='Major')
df_sorted

,Name,School,Credit_hours,Weekly_Hrs_Spent_Studying,Major
4,Lili,SOC,13,11,Advertising
7,Howard,COAS,20,16,Biology
13,Maddy,SOB,20,15,Business
6,Debby,CEA,16,17,Chemical Engineering
10,Jasmin,COAS,16,17,Chemistry
0,Jordyn,SOB,20,19,Finance
8,Jace,SOB,16,9,Finance
11,Toni,SOC,13,14,Journalism
9,Rosy,SOB,18,13,Journalism and Media
5,Sophia,SOB,18,12,Marketing
2,Kasey,CNAHS,14,8,Nursing
12,Robby,CNAHS,18,16,Nursing
3,Matthew,CNAHS,20,13,Physical Therapy
1,Alex,COAS,17,11,Physics

In [104]:
#use the credit hours to determine how much class is taken by each student
df['#_of_Classes']=df['Credit_hours']//4
df

,Name,School,Credit_hours,Weekly_Hrs_Spent_Studying,Major,#_of_Classes
0,Jordyn,SOB,20,19,Finance,5
1,Alex,COAS,17,11,Physics,4
2,Kasey,CNAHS,14,8,Nursing,3
3,Matthew,CNAHS,20,13,Physical Therapy,5
4,Lili,SOC,13,11,Advertising,3
5,Sophia,SOB,18,12,Marketing,4
6,Debby,CEA,16,17,Chemical Engineering,4
7,Howard,COAS,20,16,Biology,5
8,Jace,SOB,16,9,Finance,4
9,Rosy,SOB,18,13,Journalism and Media,4
10,Jasmin,COAS,16,17,Chemistry,4
11,Toni,SOC,13,14,Journalism,3
12,Robby,CNAHS,18,16,Nursing,4
13,Maddy,SOB,20,15,Business,5

In [105]:
#filtering the DF by showing the rows that have more than 15 credit hrs
df_filtered=df[df['Credit_hours']>15]
df_filtered

,Name,School,Credit_hours,Weekly_Hrs_Spent_Studying,Major,#_of_Classes
0,Jordyn,SOB,20,19,Finance,5
1,Alex,COAS,17,11,Physics,4
3,Matthew,CNAHS,20,13,Physical Therapy,5
5,Sophia,SOB,18,12,Marketing,4
6,Debby,CEA,16,17,Chemical Engineering,4
7,Howard,COAS,20,16,Biology,5
8,Jace,SOB,16,9,Finance,4
9,Rosy,SOB,18,13,Journalism and Media,4
10,Jasmin,COAS,16,17,Chemistry,4
12,Robby,CNAHS,18,16,Nursing,4
13,Maddy,SOB,20,15,Business,5

In [106]:
#create a new CSV file to save the filtered DF
df_new=df_filtered
df_new.to_csv('student_data_collected_filtered.csv',index=True)

In [107]:
#count how many times each major is mentioned
df.value_counts('Major')

Major
Finance                 2
Nursing                 2
Advertising             1
Biology                 1
Business                1
Chemical Engineering    1
Chemistry               1
Journalism              1
Journalism and Media    1
Marketing               1
Physical Therapy        1
Physics                 1
Name: count, dtype: int64

In [108]:
#group data by school and how many hours weekly spent studying
df_group=df.groupby('School')['Weekly_Hrs_Spent_Studying'].describe()
df_group

        count       mean       std   min    25%   50%    75%   max
School
CEA       1.0  17.000000       NaN  17.0  17.00  17.0  17.00  17.0
CNAHS     3.0  12.333333  4.041452   8.0  10.50  13.0  14.50  16.0
COAS      3.0  14.666667  3.214550  11.0  13.50  16.0  16.50  17.0
SOB       5.0  13.600000  3.714835   9.0  12.00  13.0  15.00  19.0
SOC       2.0  12.500000  2.121320  11.0  11.75  12.5  13.25  14.0

In [109]:
#describing a pattern noticed in data
print('Students in SOB make up the largest group in the dataset, but they have the lowest average study hours per week, 13.6, compared to other schools.')

Students in SOB make up the largest group in the dataset, but they have the lowest average study hours per week, 13.6, compared to other schools.