### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
n=10
np.random.seed(42)
first_name=['John','Blossom','Cass','Alex']
last_name=['Adams','Smith','Jones','Wick']
name=np.random.choice(first_name,n)+' '+np.random.choice(last_name,n)
ages=np.random.randint(18,25,n)
marks=np.random.randint(50,100,size=(n,5))
gender=np.random.choice(['Male','Female'],size=n)
student_data=pd.DataFrame(marks,columns=['Math','English','Chemistry','Biology','Physics'])
student_data

   Math  English  Chemistry  Biology  Physics
0    61       71         93       74       98
1    76       91         77       65       64
2    96       93         52       86       56
3    70       58         88       67       53
4    74       63         99       58       75
5    51       69         77       96       56
6    93       57         96       84       63
7    66       85         99       89       53
8    51       55         91       53       78
9    67       75         93       83       59

In [3]:
student_data.insert(0,'Age',ages)

In [4]:
student_data.insert(0,'Name',name)

In [5]:
student_data.insert(2,'Gender',gender)

In [6]:
student_data

            Name  Age  Gender  Math  English  Chemistry  Biology  Physics
0     Cass Jones   23  Female    61       71         93       74       98
1     Alex Jones   22  Female    76       91         77       65       64
2     John Jones   19  Female    96       93         52       86       56
3     Cass Jones   21    Male    70       58         88       67       53
4      Cass Wick   23  Female    74       63         99       58       75
5     Alex Adams   23    Male    51       69         77       96       56
6      John Wick   19  Female    93       57         96       84       63
7      John Wick   21  Female    66       85         99       89       53
8      Cass Wick   22    Male    51       55         91       53       78
9  Blossom Jones   18  Female    67       75         93       83       59

In [7]:
student_data.to_csv('student_raw_data.csv',index=False)

In [8]:
pd.read_csv('student_raw_data.csv')

            Name  Age  Gender  Math  English  Chemistry  Biology  Physics
0     Cass Jones   23  Female    61       71         93       74       98
1     Alex Jones   22  Female    76       91         77       65       64
2     John Jones   19  Female    96       93         52       86       56
3     Cass Jones   21    Male    70       58         88       67       53
4      Cass Wick   23  Female    74       63         99       58       75
5     Alex Adams   23    Male    51       69         77       96       56
6      John Wick   19  Female    93       57         96       84       63
7      John Wick   21  Female    66       85         99       89       53
8      Cass Wick   22    Male    51       55         91       53       78
9  Blossom Jones   18  Female    67       75         93       83       59

# Data_Understanding

In [9]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv('student_raw_data.csv')
df

            Name  Age  Gender  Math  English  Chemistry  Biology  Physics
0     Cass Jones   23  Female    61       71         93       74       98
1     Alex Jones   22  Female    76       91         77       65       64
2     John Jones   19  Female    96       93         52       86       56
3     Cass Jones   21    Male    70       58         88       67       53
4      Cass Wick   23  Female    74       63         99       58       75
5     Alex Adams   23    Male    51       69         77       96       56
6      John Wick   19  Female    93       57         96       84       63
7      John Wick   21  Female    66       85         99       89       53
8      Cass Wick   22    Male    51       55         91       53       78
9  Blossom Jones   18  Female    67       75         93       83       59

## Data Understanding and Preparation

In [11]:
df.head()

         Name  Age  Gender  Math  English  Chemistry  Biology  Physics
0  Cass Jones   23  Female    61       71         93       74       98
1  Alex Jones   22  Female    76       91         77       65       64
2  John Jones   19  Female    96       93         52       86       56
3  Cass Jones   21    Male    70       58         88       67       53
4   Cass Wick   23  Female    74       63         99       58       75

In [12]:
df.tail(3)

            Name  Age  Gender  Math  English  Chemistry  Biology  Physics
7      John Wick   21  Female    66       85         99       89       53
8      Cass Wick   22    Male    51       55         91       53       78
9  Blossom Jones   18  Female    67       75         93       83       59

In [13]:
df.shape

(10, 8)

In [14]:
df.size

80

In [15]:
df.columns

Index(['Name', 'Age', 'Gender', 'Math', 'English', 'Chemistry', 'Biology',
       'Physics'],
      dtype='object')

In [16]:
df.dtypes

Name         object
Age           int64
Gender       object
Math          int64
English       int64
Chemistry     int64
Biology       int64
Physics       int64
dtype: object

In [17]:
df.isnull()

    Name    Age  Gender   Math  English  Chemistry  Biology  Physics
0  False  False   False  False    False      False    False    False
1  False  False   False  False    False      False    False    False
2  False  False   False  False    False      False    False    False
3  False  False   False  False    False      False    False    False
4  False  False   False  False    False      False    False    False
5  False  False   False  False    False      False    False    False
6  False  False   False  False    False      False    False    False
7  False  False   False  False    False      False    False    False
8  False  False   False  False    False      False    False    False
9  False  False   False  False    False      False    False    False

In [18]:
df.isnull().sum()

Name         0
Age          0
Gender       0
Math         0
English      0
Chemistry    0
Biology      0
Physics      0
dtype: int64

In [19]:
print(df.isnull().sum().sum())

0

In [20]:
df[['Name','Math']]

            Name  Math
0     Cass Jones    61
1     Alex Jones    76
2     John Jones    96
3     Cass Jones    70
4      Cass Wick    74
5     Alex Adams    51
6      John Wick    93
7      John Wick    66
8      Cass Wick    51
9  Blossom Jones    67

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       10 non-null     object
 1   Age        10 non-null     int64
 2   Gender     10 non-null     object
 3   Math       10 non-null     int64
 4   English    10 non-null     int64
 5   Chemistry  10 non-null     int64
 6   Biology    10 non-null     int64
 7   Physics    10 non-null     int64
dtypes: int64(6), object(2)
memory usage: 772.0+ bytes

In [22]:
print(df['Gender'].unique())

['Female' 'Male']

In [23]:
print(df['Name'].unique())

['Cass Jones' 'Alex Jones' 'John Jones' 'Cass Wick' 'Alex Adams'
 'John Wick' 'Blossom Jones']

In [24]:
df['Name'].duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8     True
9    False
Name: Name, dtype: bool

In [25]:
df

            Name  Age  Gender  Math  English  Chemistry  Biology  Physics
0     Cass Jones   23  Female    61       71         93       74       98
1     Alex Jones   22  Female    76       91         77       65       64
2     John Jones   19  Female    96       93         52       86       56
3     Cass Jones   21    Male    70       58         88       67       53
4      Cass Wick   23  Female    74       63         99       58       75
5     Alex Adams   23    Male    51       69         77       96       56
6      John Wick   19  Female    93       57         96       84       63
7      John Wick   21  Female    66       85         99       89       53
8      Cass Wick   22    Male    51       55         91       53       78
9  Blossom Jones   18  Female    67       75         93       83       59

# Filtering Data

In [26]:
df_new=df.copy()
df_new

            Name  Age  Gender  Math  English  Chemistry  Biology  Physics
0     Cass Jones   23  Female    61       71         93       74       98
1     Alex Jones   22  Female    76       91         77       65       64
2     John Jones   19  Female    96       93         52       86       56
3     Cass Jones   21    Male    70       58         88       67       53
4      Cass Wick   23  Female    74       63         99       58       75
5     Alex Adams   23    Male    51       69         77       96       56
6      John Wick   19  Female    93       57         96       84       63
7      John Wick   21  Female    66       85         99       89       53
8      Cass Wick   22    Male    51       55         91       53       78
9  Blossom Jones   18  Female    67       75         93       83       59

In [27]:
df_new['Age']

0    23
1    22
2    19
3    21
4    23
5    23
6    19
7    21
8    22
9    18
Name: Age, dtype: int64

In [28]:
#df_new['Total']=df_new['Math']+df_new['English']+df_new['Chemistry']+df_new['Biology']+df_new['Physics']
df_new['Total']=df_new[['Math','English','Chemistry','Biology','Physics']].sum(axis=1)

In [29]:
df_new

,Name,Age,Gender,Math,English,Chemistry,Biology,Physics,Total
0,Cass Jones,23,Female,61,71,93,74,98,397
1,Alex Jones,22,Female,76,91,77,65,64,373
2,John Jones,19,Female,96,93,52,86,56,383
3,Cass Jones,21,Male,70,58,88,67,53,336
4,Cass Wick,23,Female,74,63,99,58,75,369
5,Alex Adams,23,Male,51,69,77,96,56,349
6,John Wick,19,Female,93,57,96,84,63,393
7,John Wick,21,Female,66,85,99,89,53,392
8,Cass Wick,22,Male,51,55,91,53,78,328
9,Blossom Jones,18,Female,67,75,93,83,59,377

In [30]:
df_new['Sci_total']=df_new[['Chemistry','Biology','Physics']].sum(axis=1)
df_new['Percentage']=(df_new['Total']/500)*100
df_new

,Name,Age,Gender,Math,English,Chemistry,Biology,Physics,Total,Sci_total,Percentage
0,Cass Jones,23,Female,61,71,93,74,98,397,265,79.4
1,Alex Jones,22,Female,76,91,77,65,64,373,206,74.6
2,John Jones,19,Female,96,93,52,86,56,383,194,76.6
3,Cass Jones,21,Male,70,58,88,67,53,336,208,67.2
4,Cass Wick,23,Female,74,63,99,58,75,369,232,73.8
5,Alex Adams,23,Male,51,69,77,96,56,349,229,69.8
6,John Wick,19,Female,93,57,96,84,63,393,243,78.6
7,John Wick,21,Female,66,85,99,89,53,392,241,78.4
8,Cass Wick,22,Male,51,55,91,53,78,328,222,65.6
9,Blossom Jones,18,Female,67,75,93,83,59,377,235,75.4

In [31]:
def grade(percentage):
    if percentage >=90:
        return 'A'
    elif percentage >=80:
        return 'B'
    elif percentage >=70:
        return 'C'
    elif percentage >=60:
        return 'D'
    else:
        return 'F'

In [32]:
df_new['Grade']=df_new['Percentage'].apply(grade)
df_new

,Name,Age,Gender,Math,English,Chemistry,Biology,Physics,Total,Sci_total,Percentage,Grade
0,Cass Jones,23,Female,61,71,93,74,98,397,265,79.4,C
1,Alex Jones,22,Female,76,91,77,65,64,373,206,74.6,C
2,John Jones,19,Female,96,93,52,86,56,383,194,76.6,C
3,Cass Jones,21,Male,70,58,88,67,53,336,208,67.2,D
4,Cass Wick,23,Female,74,63,99,58,75,369,232,73.8,C
5,Alex Adams,23,Male,51,69,77,96,56,349,229,69.8,D
6,John Wick,19,Female,93,57,96,84,63,393,243,78.6,C
7,John Wick,21,Female,66,85,99,89,53,392,241,78.4,C
8,Cass Wick,22,Male,51,55,91,53,78,328,222,65.6,D
9,Blossom Jones,18,Female,67,75,93,83,59,377,235,75.4,C

In [33]:
df_new['Percentage_bonus']=df_new['Percentage'].apply(lambda x:x+5)
df_new

,Name,Age,Gender,Math,English,Chemistry,Biology,Physics,Total,Sci_total,Percentage,Grade,Percentage_bonus
0,Cass Jones,23,Female,61,71,93,74,98,397,265,79.4,C,84.4
1,Alex Jones,22,Female,76,91,77,65,64,373,206,74.6,C,79.6
2,John Jones,19,Female,96,93,52,86,56,383,194,76.6,C,81.6
3,Cass Jones,21,Male,70,58,88,67,53,336,208,67.2,D,72.2
4,Cass Wick,23,Female,74,63,99,58,75,369,232,73.8,C,78.8
5,Alex Adams,23,Male,51,69,77,96,56,349,229,69.8,D,74.8
6,John Wick,19,Female,93,57,96,84,63,393,243,78.6,C,83.6
7,John Wick,21,Female,66,85,99,89,53,392,241,78.4,C,83.4
8,Cass Wick,22,Male,51,55,91,53,78,328,222,65.6,D,70.6
9,Blossom Jones,18,Female,67,75,93,83,59,377,235,75.4,C,80.4

In [34]:
print('Data Frame before dropping bonus column:\n', df_new)
df_new.drop(columns=['Percentage_bonus'],inplace=True)
print('Data Frame after dropping bonus column:\n', df_new)

Data Frame before dropping bonus column:
             Name  Age  Gender  Math  English  Chemistry  Biology  Physics  \
0     Cass Jones   23  Female    61       71         93       74       98
1     Alex Jones   22  Female    76       91         77       65       64
2     John Jones   19  Female    96       93         52       86       56
3     Cass Jones   21    Male    70       58         88       67       53
4      Cass Wick   23  Female    74       63         99       58       75
5     Alex Adams   23    Male    51       69         77       96       56
6      John Wick   19  Female    93       57         96       84       63
7      John Wick   21  Female    66       85         99       89       53
8      Cass Wick   22    Male    51       55         91       53       78
9  Blossom Jones   18  Female    67       75         93       83       59

   Total  Sci_total  Percentage Grade  Percentage_bonus
0    397        265        79.4     C              84.4
1    373        206        74.6     C              79.6
2    383        194        76.6     C              81.6
3    336        208        67.2     D              72.2
4    369        232        73.8     C              78.8
5    349        229        69.8     D              74.8
6    393        243        78.6     C              83.6
7    392        241        78.4     C              83.4
8    328        222        65.6     D              70.6
9    377        235        75.4     C              80.4
Data Frame after dropping bonus column:
             Name  Age  Gender  Math  English  Chemistry  Biology  Physics  \
0     Cass Jones   23  Female    61       71         93       74       98
1     Alex Jones   22  Female    76       91         77       65       64
2     John Jones   19  Female    96       93         52       86       56
3     Cass Jones   21    Male    70       58         88       67       53
4      Cass Wick   23  Female    74       63         99       58       75
5     Alex Adams   23    Male    51       69         77       96       56
6      John Wick   19  Female    93       57         96       84       63
7      John Wick   21  Female    66       85         99       89       53
8      Cass Wick   22    Male    51       55         91       53       78
9  Blossom Jones   18  Female    67       75         93       83       59

   Total  Sci_total  Percentage Grade
0    397        265        79.4     C
1    373        206        74.6     C
2    383        194        76.6     C
3    336        208        67.2     D
4    369        232        73.8     C
5    349        229        69.8     D
6    393        243        78.6     C
7    392        241        78.4     C
8    328        222        65.6     D
9    377        235        75.4     C

In [35]:
df_new

,Name,Age,Gender,Math,English,Chemistry,Biology,Physics,Total,Sci_total,Percentage,Grade
0,Cass Jones,23,Female,61,71,93,74,98,397,265,79.4,C
1,Alex Jones,22,Female,76,91,77,65,64,373,206,74.6,C
2,John Jones,19,Female,96,93,52,86,56,383,194,76.6,C
3,Cass Jones,21,Male,70,58,88,67,53,336,208,67.2,D
4,Cass Wick,23,Female,74,63,99,58,75,369,232,73.8,C
5,Alex Adams,23,Male,51,69,77,96,56,349,229,69.8,D
6,John Wick,19,Female,93,57,96,84,63,393,243,78.6,C
7,John Wick,21,Female,66,85,99,89,53,392,241,78.4,C
8,Cass Wick,22,Male,51,55,91,53,78,328,222,65.6,D
9,Blossom Jones,18,Female,67,75,93,83,59,377,235,75.4,C

In [36]:
# Indexing

In [37]:
df_filtered=df_new[df_new['Chemistry']>90]
df_filtered

,Name,Age,Gender,Math,English,Chemistry,Biology,Physics,Total,Sci_total,Percentage,Grade
0,Cass Jones,23,Female,61,71,93,74,98,397,265,79.4,C
4,Cass Wick,23,Female,74,63,99,58,75,369,232,73.8,C
6,John Wick,19,Female,93,57,96,84,63,393,243,78.6,C
7,John Wick,21,Female,66,85,99,89,53,392,241,78.4,C
8,Cass Wick,22,Male,51,55,91,53,78,328,222,65.6,D
9,Blossom Jones,18,Female,67,75,93,83,59,377,235,75.4,C

In [38]:
filtered_df=df_new[(df_new['Chemistry']>80)&(df_new['Math']>80)]
filtered_df

,Name,Age,Gender,Math,English,Chemistry,Biology,Physics,Total,Sci_total,Percentage,Grade
6,John Wick,19,Female,93,57,96,84,63,393,243,78.6,C

In [39]:
df_new.rename(columns={'Name':'Student_Name'},inplace=True)
df_new

,Student_Name,Age,Gender,Math,English,Chemistry,Biology,Physics,Total,Sci_total,Percentage,Grade
0,Cass Jones,23,Female,61,71,93,74,98,397,265,79.4,C
1,Alex Jones,22,Female,76,91,77,65,64,373,206,74.6,C
2,John Jones,19,Female,96,93,52,86,56,383,194,76.6,C
3,Cass Jones,21,Male,70,58,88,67,53,336,208,67.2,D
4,Cass Wick,23,Female,74,63,99,58,75,369,232,73.8,C
5,Alex Adams,23,Male,51,69,77,96,56,349,229,69.8,D
6,John Wick,19,Female,93,57,96,84,63,393,243,78.6,C
7,John Wick,21,Female,66,85,99,89,53,392,241,78.4,C
8,Cass Wick,22,Male,51,55,91,53,78,328,222,65.6,D
9,Blossom Jones,18,Female,67,75,93,83,59,377,235,75.4,C

In [40]:
df_index=df_new.set_index('Student_Name')
df_index

,Age,Gender,Math,English,Chemistry,Biology,Physics,Total,Sci_total,Percentage,Grade
Student_Name,,,,,,,,,,,
Cass Jones,23,Female,61,71,93,74,98,397,265,79.4,C
Alex Jones,22,Female,76,91,77,65,64,373,206,74.6,C
John Jones,19,Female,96,93,52,86,56,383,194,76.6,C
Cass Jones,21,Male,70,58,88,67,53,336,208,67.2,D
Cass Wick,23,Female,74,63,99,58,75,369,232,73.8,C
Alex Adams,23,Male,51,69,77,96,56,349,229,69.8,D
John Wick,19,Female,93,57,96,84,63,393,243,78.6,C
John Wick,21,Female,66,85,99,89,53,392,241,78.4,C
Cass Wick,22,Male,51,55,91,53,78,328,222,65.6,D
Blossom Jones,18,Female,67,75,93,83,59,377,235,75.4,C

In [41]:
df_new.to_csv('student_raw_data_new.csv',index=False)